### ISSUE TITLE
Created plots are visually to close to each other

### ISSUE THREAD

**Issue by Tdannen** [QuantLet/QID-1481-MVAlaplacedis#2]

**Comment by polarstern** [comment]
done, images should be updated

![mvalaplacedis_1-1](https://cloud.githubusercontent.com/assets/14127572/9851609/d9066ca0-5af9-11e5-985d-0c11148fdfae.png)
![mvalaplacedis_2-1](https://cloud.githubusercontent.com/assets/14127572/9851610/d91d413c-5af9-11e5-9f05-272702dfd6ed.png)

**Comment by Tdannen** [comment]
Plots look fantastic.
Uploaded images in Issues can easily be saved via 'save as'.
I will upload them to the correct repository
